server:
  port: 9998
spring:
  application:
    name: kafka-producer
  cloud:
    stream:
      kafka:
        binder:
          defaultZkPort: 2181
          brokers: 192.168.99.100
          defaultBrokerPort: 9092